version: '3.3'

services:
    redisinsight-app:
        image: redislabs/redisinsight:latest
        container_name: redisinsight
        networks:
            - redisinsight-network

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8001:8001"
        networks:
            - redisinsight-network



#Docker Networks
networks:
    redisinsight-network:
      driver: bridge